import os
import asyncio
from telethon import TelegramClient

async def run_tg_osint(tg_id: str, send_log, report_results):
    await send_log(f"[+] Starting REAL TELEGRAM OSINT lookup for ID: {tg_id}")
    
    api_id = os.getenv("TG_API_ID")
    api_hash = os.getenv("TG_API_HASH")
    
    if not api_id or not api_hash:
        await send_log("[!] TG_API_ID or TG_API_HASH missing in .env.")
        await send_log("[!] To use proper MTProto OSINT, add your credentials from my.telegram.org")
        await report_results("Telegram Intel (MTProto)", {"error": "Missing API Credentials. Set TG_API_ID and TG_API_HASH in .env"})
        return
        
    results = {}
    
    # Define client using the existing osint_session generated by init_tg.py
    # We set loop directly to asyncio's running loop
    client = TelegramClient('osint_session', int(api_id), api_hash)
    
    try:
        await send_log(f"[TELEGRAM] Initiating pure MTProto connection to Telegram DC...")
        # Telethon needs to connect. 
        await client.connect()
        
        if not await client.is_user_authorized():
            await send_log("[!] Telegram session is not authorized. Run 'python init_tg.py' in the console first to login.")
            results["error"] = "Unauthorized local MTProto session"
        else:
            await send_log(f"[TELEGRAM] Session authorized. Requesting Entity details from Telegram Core...")
            try:
                # MTProto extraction logic
                from telethon.tl.functions.users import GetFullUserRequest
                from telethon.tl.functions.messages import GetCommonChatsRequest
                
                user_id_int = int(tg_id)
                entity = await client.get_entity(user_id_int)
                
                # Get full user data (for Bio)
                full_user = await client(GetFullUserRequest(id=entity))
                bio = getattr(full_user.full_user, 'about', None)
                
                # Retrieve common groups
                common_chats_info = await client(GetCommonChatsRequest(user_id=entity, max_id=0, limit=100))
                common_groups = [chat.title for chat in common_chats_info.chats]
                
                results["telegram_entity"] = {
                    "id": entity.id,
                    "first_name": getattr(entity, 'first_name', None),
                    "last_name": getattr(entity, 'last_name', None),
                    "username": getattr(entity, 'username', None),
                    "phone": getattr(entity, 'phone', None),
                    "bio": bio,
                    "is_bot": getattr(entity, 'bot', False),
                    "is_premium": getattr(entity, 'premium', False),
                    "restricted": getattr(entity, 'restricted', False),
                    "common_groups": common_groups
                }
                
                await send_log(f"[TELEGRAM] Target Entity extracted successfully!")
                await send_log(f"[TELEGRAM] => Username: {results['telegram_entity']['username']}")
                await send_log(f"[TELEGRAM] => Name: {results['telegram_entity']['first_name']}")
                if bio:
                    await send_log(f"[TELEGRAM] => Bio: {bio}")
                if common_groups:
                    await send_log(f"[TELEGRAM] => Found {len(common_groups)} common groups!")
                if results['telegram_entity']['phone']:
                     await send_log(f"[TELEGRAM] => Phone Number EXPOSED: +{results['telegram_entity']['phone']}")
                     
            except ValueError as ve:
                await send_log(f"[!] Target not found in Telegram's cache.")
                await send_log(f"[!] TELEGRAM API RESTRICTION: You can only resolve numeric IDs for users you share a chat with or have interacted with before.")
                results["error"] = "Entity not found (Telegram Privacy Restriction)"
                
    except Exception as e:
        await send_log(f"[!] Exception during Telegram OSINT: {type(e).__name__} - {str(e)}")
        results["error"] = str(e)
    finally:
        await client.disconnect()
        
    await send_log(f"[-] TELEGRAM scan completed.")
    await report_results("Telegram Intel (MTProto)", results)
